const express=require('express'),router=express.Router(),{db}=require('../db');
const {translateGrammarSentence}=require('../utils/grammar-translation');
const ach=require('../utils/achievements');
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const parseOptions=v=>{try{const x=typeof v==='string'?JSON.parse(v):v;return Array.isArray(x)?x:[]}catch{return[]}};
let ready;const schema=()=>ready||(ready=db.pool.query("CREATE TABLE IF NOT EXISTS adventure_course_progress(id INT PRIMARY KEY AUTO_INCREMENT,user_id INT NOT NULL,level_key VARCHAR(80) NOT NULL,status VARCHAR(20) DEFAULT 'not_started',best_score INT DEFAULT 0,stars INT DEFAULT 0,attempts INT DEFAULT 0,passed_at TIMESTAMP NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_course_level(user_id,level_key),INDEX idx_course_user(user_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"));
const scenes=['初次见面','自我介绍','家庭成员','日常作息','时间日期','校园生活','兴趣爱好','食物饮料','餐厅点餐','购物消费','城市问路','交通出行','天气季节','住房家居','健康就医','朋友社交','旅行计划','酒店住宿','工作职场','电话沟通','文化娱乐','新闻媒体','环境自然','情绪观点'];
const worldOf=n=>n<=20?['A1','生存英语']:n<=45?['A2','日常交流']:n<=70?['B1','独立表达']:n<=95?['B2','深入沟通']:['C1','复杂应用'];
function specs(scene){if(scene===121)return[{type:'boss'}];const list=[];if(scene<=16)for(let i=0;i<3;i++)list.push({type:'phonetic',index:(scene-1)*3+i});for(let i=0;i<30;i++)list.push({type:'word',index:(scene-1)*30+i});list.push({type:'grammar',round:0},{type:'grammar',round:1},{type:'listen'},{type:'review'},{type:'boss'});return list}
function modules(){return Array.from({length:120},(_,i)=>{const n=i+1,[world,stage]=worldOf(n),title=scenes[i%scenes.length]+(i>=scenes.length?' '+(Math.floor(i/scenes.length)+1):'');return{key:'scene-'+String(n).padStart(3,'0'),type:'scene',moduleNo:n,world,stage,title,subtitle:stage+' · 从理解到真实表达',icon:n%6===0?'🏆':['👋','🏠','🕐','🍽️','🛍️','🚌'][i%6],color:'#1f6f78',itemStart:(n-1)*300+1,itemEnd:n*300,totalLevels:specs(n).length}})}
async function allModules(uid){await schema();await ach.ensureTables();const ms=modules(),boss=await db.prepare('SELECT 1 FROM user_rewards WHERE user_id=? AND reward_type=? AND count>0').get(uid,'boss_key');if(boss)ms.push({key:'boss-001',type:'boss',moduleNo:121,world:'隐藏',stage:'Boss 战',title:'隐藏 Boss 关',subtitle:'集齐全部成就解锁的终极挑战',icon:'👑',color:'#7c3aed',itemStart:1,itemEnd:1,totalLevels:1});const rows=await db.prepare('SELECT level_key,status,stars FROM adventure_course_progress WHERE user_id=?').all(uid),map=new Map(rows.map(x=>[x.level_key,x]));let prior=true;for(const m of ms){m.passedLevels=0;m.stars=0;let started=0;for(let i=1;i<=m.totalLevels;i++){const x=map.get(m.key+'-'+String(i).padStart(3,'0'));if(x)started++;if(x?.status==='passed')m.passedLevels++;m.stars+=+x?.stars||0}m.completed=m.passedLevels===m.totalLevels;if(m.key==='boss-001'){m.unlocked=true;m.status=m.completed?'passed':(started?'learning':'not_started')}else{m.unlocked=m.moduleNo===1||prior;m.status=m.completed?'passed':m.unlocked?(started?'learning':'not_started'):'locked';prior=prior&&m.completed}}return ms}
router.get('/modules',async(req,res)=>{try{const modules=await allModules(+req.query.userId),passedModules=modules.filter(x=>x.completed).length,totalLevels=modules.reduce((a,x)=>a+x.totalLevels,0),passedLevels=modules.reduce((a,x)=>a+x.passedLevels,0);res.json({code:0,data:{modules,current:modules.find(x=>x.unlocked&&!x.completed),passedModules,totalModules:modules.length,passedCount:passedModules,total:modules.length,totalLevels,passedLevels,stars:modules.reduce((a,x)=>a+x.stars,0)}})}catch(e){console.error(e);res.status(500).json({code:500,message:'加载成长路线失败'})}});
function label(m,n){if(m.key==='boss-001')return'终极 Boss 战';const s=specs(m.moduleNo)[n-1];if(!s)return'';if(s.type==='phonetic')return'音标启蒙 · 第'+(s.index+1)+'个';if(s.type==='word')return'场景词汇 · '+(s.index*10+1)+'-'+(s.index*10+10);if(s.type==='grammar')return'场景语法 · 专项练习';if(s.type==='listen')return'场景听力 · 听懂对话';if(s.type==='review')return'融合复习 · 查漏补缺';return'场景挑战 · 综合通关'}
router.get('/module/:key/levels',async(req,res)=>{try{const uid=+req.query.userId,ms=await allModules(uid),m=ms.find(x=>x.key===req.params.key);if(!m)return res.status(404).json({code:404,message:'场景不存在'});if(!m.unlocked)return res.status(403).json({code:403,message:'请先通过上一个场景'});const rows=await db.prepare('SELECT * FROM adventure_course_progress WHERE user_id=? AND level_key LIKE ?').all(uid,m.key+'-%'),map=new Map(rows.map(x=>[x.level_key,x]));let prior=true;const levels=Array.from({length:m.totalLevels},(_,i)=>{const n=i+1,key=m.key+'-'+String(n).padStart(3,'0'),x=map.get(key),passed=x?.status==='passed',unlocked=n===1||prior;prior=prior&&passed;return{key,levelNo:n,title:n===m.totalLevels?(m.key==='boss-001'?'终极 Boss 战':'场景挑战'):'第 '+n+' 关',subtitle:label(m,n),status:passed?'passed':unlocked?(x?.status||'not_started'):'locked',unlocked,stars:+x?.stars||0,bestScore:+x?.best_score||0,isBoss:n===m.totalLevels}});res.json({code:0,data:{module:m,levels}})}catch(e){console.error(e);res.status(500).json({code:500,message:'加载场景关卡失败'})}});
function parse(key){const x=String(key).match(/^(scene-([0-9]{3})|boss-([0-9]{3}))-([0-9]{3})$/);if(!x)return null;return{scene:+x[2]||121,level:+x[4],moduleKey:x[1]}}
async function check(uid,key){const p=parse(key);if(!p)throw Error('关卡编号无效');const ms=await allModules(uid),m=ms.find(x=>x.key===p.moduleKey);if(!m||p.level<1||p.level>m.totalLevels)throw Error('关卡不存在');if(!m.unlocked)throw Error('场景尚未解锁');if(p.level>1){const k=m.key+'-'+String(p.level-1).padStart(3,'0'),x=await db.prepare('SELECT status FROM adventure_course_progress WHERE user_id=? AND level_key=?').get(uid,k);if(x?.status!=='passed')throw Error('请先通过上一关')}return{p,m,spec:specs(p.scene)[p.level-1]}}
async function wordQs(index,count=10){const off=index*10,ws=await db.prepare("SELECT id,word,phonetic_us,chinese FROM words WHERE chinese IS NOT NULL AND chinese<>'' ORDER BY CASE WHEN frequency_rank IS NULL THEN 1 ELSE 0 END,frequency_rank,sort_order,id LIMIT ? OFFSET ?").all(count,off),ds=await db.prepare("SELECT chinese FROM words WHERE chinese IS NOT NULL AND chinese<>'' ORDER BY RAND() LIMIT 40").all();return ws.map((x,i)=>({id:'w-'+x.id,type:i%3===1?'listen':'word',prompt:i%3===1?'听发音，选择正确的单词':x.word,audioText:i%3===1?x.word:'',phonetic:x.phonetic_us,translation:x.chinese,options:i%3===1?shuffle([x.word,...ws.filter(y=>y.id!==x.id).slice(0,3).map(y=>y.word)]):shuffle([x.chinese,...ds.map(y=>y.chinese).filter(y=>y!==x.chinese).slice(0,3)]),answer:i%3===1?x.word:x.chinese,explanation:x.word+'：'+x.chinese}))}
async function grammarQs(scene,round,count=10){const pointOffset=Math.min(34,Math.floor((scene-1)*35/120)),[point]=await db.prepare('SELECT id,title FROM grammar_points ORDER BY stage,sort_order,id LIMIT 1 OFFSET ?').all(pointOffset);if(!point)return[];const rs=await db.prepare('SELECT * FROM grammar_questions WHERE grammar_id=? ORDER BY sort_order,id LIMIT ? OFFSET ?').all(point.id,count,round*10);return rs.map(x=>({id:'g-'+x.id,type:'grammar',prompt:x.sentence,translation:translateGrammarSentence(x),options:shuffle(parseOptions(x.options)),answer:x.answer,explanation:x.explanation||point.title}))}
async function listenQs(scene,count=0){const off=scene<=20?(scene-1)*6:120+(scene-21)*5,limit=count||(scene<=20?6:5),rs=await db.prepare('SELECT id,text,chinese FROM shadow_sentences ORDER BY sort_order,id LIMIT ? OFFSET ?').all(limit,off),ds=await db.prepare('SELECT chinese FROM shadow_sentences ORDER BY RAND() LIMIT 30').all();return rs.map(x=>({id:'l-'+x.id,type:'listen',prompt:'听句子，选择正确的中文含义',audioText:x.text,options:shuffle([x.chinese,...ds.map(y=>y.chinese).filter(y=>y!==x.chinese).slice(0,3)]),answer:x.chinese,explanation:x.text+'：'+x.chinese}))}
async function makeQs(p,s){if(s.type==='word')return wordQs(s.index);if(s.type==='grammar')return grammarQs(p.scene,s.round);if(s.type==='listen')return listenQs(p.scene);if(s.type==='review')return shuffle([...(await wordQs((p.scene-1)*30+29,5)),...(await grammarQs(p.scene,2,5))]);if(s.type==='boss')return shuffle([...(await wordQs(719,4)),...(await grammarQs(24,3,3)),...(await listenQs(24,3))]);const [x]=await db.prepare('SELECT * FROM phonetics ORDER BY sort_order,id LIMIT 1 OFFSET ?').all(s.index),os=x?await db.prepare('SELECT * FROM phonetics WHERE id<>? ORDER BY RAND() LIMIT 6').all(x.id):[];return x?[{id:'p1-'+x.id,type:'phonetic',prompt:'选择音标 '+x.symbol+' 的示例词',audioText:x.example,options:shuffle([x.example,...os.slice(0,3).map(y=>y.example)]),answer:x.example,explanation:x.symbol+'：'+x.example},{id:'p2-'+x.id,type:'phonetic',prompt:'听发音，选择对应音标',audioText:x.example,options:shuffle([x.symbol,...os.slice(0,3).map(y=>y.symbol)]),answer:x.symbol,explanation:x.example+' 包含音标 '+x.symbol}]:[]}
router.get('/level/:key/questions',async(req,res)=>{try{const uid=+req.query.userId,{p,m,spec}=await check(uid,req.params.key),qs=await makeQs(p,spec);if(!qs.length)return res.status(503).json({code:503,message:'当前关卡题目不足'});await db.prepare("INSERT INTO adventure_course_progress(user_id,level_key,status) VALUES (?,?,'learning') ON DUPLICATE KEY UPDATE status=IF(status='passed',status,'learning')").run(uid,req.params.key);res.json({code:0,data:{level:{key:req.params.key,levelNo:p.level,title:label(m,p.level),moduleTitle:m.title},questions:qs,passScore:80}})}catch(e){res.status(400).json({code:400,message:e.message})}});
router.post('/level/:key/submit',async(req,res)=>{try{const uid=+req.body.userId,{p,m}=await check(uid,req.params.key),a=Array.isArray(req.body.answers)?req.body.answers:[],correct=a.filter(x=>x.correct===true).length,score=a.length?Math.round(correct*100/a.length):0,passed0=a.length>0&&score>=80;let shieldUsed=false;if(!passed0){await ach.ensureTables();const shield=await db.prepare('SELECT count FROM user_rewards WHERE user_id=? AND reward_type=? AND count>0').get(uid,'star_shield');if(shield){shieldUsed=true;await db.prepare('UPDATE user_rewards SET count=count-1 WHERE user_id=? AND reward_type=?').run(uid,'star_shield')}}const passed=passed0||shieldUsed,stars=passed?(score>=95?3:score>=85?2:1):0,old=await db.prepare('SELECT best_score,stars FROM adventure_course_progress WHERE user_id=? AND level_key=?').get(uid,req.params.key),best=Math.max(score,+old?.best_score||0),bestStars=Math.max(stars,+old?.stars||0);await db.prepare("INSERT INTO adventure_course_progress(user_id,level_key,status,best_score,stars,attempts,passed_at) VALUES (?,?,?,?,?,1,IF(?=1,CURRENT_TIMESTAMP,NULL)) ON DUPLICATE KEY UPDATE status=IF(status='passed','passed',VALUES(status)),best_score=GREATEST(best_score,VALUES(best_score)),stars=GREATEST(stars,VALUES(stars)),attempts=attempts+1,passed_at=IF(passed_at IS NULL AND VALUES(status)='passed',CURRENT_TIMESTAMP,passed_at)").run(uid,req.params.key,passed?'passed':'learning',best,bestStars,passed?1:0);let combo=0,cur=0;for(const item of a){cur=(item.correct===true)?cur+1:0;if(cur>combo)combo=cur}await ach.maybeUnlockCombo(uid,combo);await ach.maybeUnlockMorningScholar(uid);res.json({code:0,data:{passed,score,correct,total:a.length,stars:bestStars,bestScore:best,shieldUsed,next:passed&&p.level<m.totalLevels?m.key+'-'+String(p.level+1).padStart(3,'0'):null,moduleKey:m.key,moduleCompleted:passed&&p.level===m.totalLevels}})}catch(e){res.status(400).json({code:400,message:e.message})}});
module.exports=router;