const { db, initDatabase } = require('./database-sqlite');

// 单词数据
const words = [
	// ===== level 0: 基础词汇 =====
	{ word: 'hello', phonetic_us: '/həˈloʊ/', phonetic_uk: '/həˈləʊ/', chinese: '你好', example: 'Hello, how are you?', level: 0, tag: '问候' },
	{ word: 'goodbye', phonetic_us: '/ɡʊdˈbaɪ/', phonetic_uk: '/ɡʊdˈbaɪ/', chinese: '再见', example: 'Goodbye, see you tomorrow.', level: 0, tag: '问候' },
	{ word: 'thank', phonetic_us: '/θæŋk/', phonetic_uk: '/θæŋk/', chinese: '感谢', example: 'Thank you very much.', level: 0, tag: '礼貌' },
	{ word: 'please', phonetic_us: '/pliːz/', phonetic_uk: '/pliːz/', chinese: '请', example: 'Please sit down.', level: 0, tag: '礼貌' },
	{ word: 'sorry', phonetic_us: '/ˈsɑːri/', phonetic_uk: '/ˈsɒri/', chinese: '对不起', example: 'I am sorry for being late.', level: 0, tag: '礼貌' },
	{ word: 'good', phonetic_us: '/ɡʊd/', phonetic_uk: '/ɡʊd/', chinese: '好的', example: 'Good morning!', level: 0, tag: '形容' },
	{ word: 'bad', phonetic_us: '/bæd/', phonetic_uk: '/bæd/', chinese: '坏的', example: 'That is a bad idea.', level: 0, tag: '形容' },
	{ word: 'big', phonetic_us: '/bɪɡ/', phonetic_uk: '/bɪɡ/', chinese: '大的', example: 'This is a big house.', level: 0, tag: '形容' },
	{ word: 'small', phonetic_us: '/smɔːl/', phonetic_uk: '/smɔːl/', chinese: '小的', example: 'I have a small dog.', level: 0, tag: '形容' },
	{ word: 'hot', phonetic_us: '/hɑːt/', phonetic_uk: '/hɒt/', chinese: '热的', example: 'It is very hot today.', level: 0, tag: '形容' },
	{ word: 'cold', phonetic_us: '/koʊld/', phonetic_uk: '/kəʊld/', chinese: '冷的', example: 'The water is cold.', level: 0, tag: '形容' },
	{ word: 'happy', phonetic_us: '/ˈhæpi/', phonetic_uk: '/ˈhæpi/', chinese: '快乐的', example: 'I am very happy today.', level: 0, tag: '情感' },
	{ word: 'sad', phonetic_us: '/sæd/', phonetic_uk: '/sæd/', chinese: '悲伤的', example: 'She looks sad.', level: 0, tag: '情感' },
	{ word: 'love', phonetic_us: '/lʌv/', phonetic_uk: '/lʌv/', chinese: '爱', example: 'I love you very much.', level: 0, tag: '情感' },
	{ word: 'like', phonetic_us: '/laɪk/', phonetic_uk: '/laɪk/', chinese: '喜欢', example: 'I like ice cream.', level: 0, tag: '情感' },
	{ word: 'want', phonetic_us: '/wɑːnt/', phonetic_uk: '/wɒnt/', chinese: '想要', example: 'I want to go home.', level: 0, tag: '动词' },
	{ word: 'need', phonetic_us: '/niːd/', phonetic_uk: '/niːd/', chinese: '需要', example: 'I need your help.', level: 0, tag: '动词' },
	{ word: 'have', phonetic_us: '/hæv/', phonetic_uk: '/hæv/', chinese: '有', example: 'I have a cat.', level: 0, tag: '动词' },
	{ word: 'make', phonetic_us: '/meɪk/', phonetic_uk: '/meɪk/', chinese: '制作', example: 'I can make a cake.', level: 0, tag: '动词' },
	{ word: 'go', phonetic_us: '/ɡoʊ/', phonetic_uk: '/ɡəʊ/', chinese: '去', example: 'Let us go to the park.', level: 0, tag: '动词' },
	{ word: 'come', phonetic_us: '/kʌm/', phonetic_uk: '/kʌm/', chinese: '来', example: 'Come here, please.', level: 0, tag: '动词' },
	{ word: 'see', phonetic_us: '/siː/', phonetic_uk: '/siː/', chinese: '看见', example: 'I can see the bird.', level: 0, tag: '动词' },
	{ word: 'look', phonetic_us: '/lʊk/', phonetic_uk: '/lʊk/', chinese: '看', example: 'Look at this picture.', level: 0, tag: '动词' },
	{ word: 'eat', phonetic_us: '/iːt/', phonetic_uk: '/iːt/', chinese: '吃', example: 'I want to eat lunch.', level: 0, tag: '动词' },
	{ word: 'drink', phonetic_us: '/drɪŋk/', phonetic_uk: '/drɪŋk/', chinese: '喝', example: 'I need to drink water.', level: 0, tag: '动词' },
	{ word: 'sleep', phonetic_us: '/sliːp/', phonetic_uk: '/sliːp/', chinese: '睡觉', example: 'I sleep at 10 PM.', level: 0, tag: '动词' },
	{ word: 'work', phonetic_us: '/wɜːrk/', phonetic_uk: '/wɜːk/', chinese: '工作', example: 'I go to work by bus.', level: 0, tag: '动词' },
	{ word: 'play', phonetic_us: '/pleɪ/', phonetic_uk: '/pleɪ/', chinese: '玩', example: 'Children like to play.', level: 0, tag: '动词' },
	{ word: 'read', phonetic_us: '/riːd/', phonetic_uk: '/riːd/', chinese: '读', example: 'I read a book every day.', level: 0, tag: '动词' },
	{ word: 'write', phonetic_us: '/raɪt/', phonetic_uk: '/raɪt/', chinese: '写', example: 'Please write your name.', level: 0, tag: '动词' },
	{ word: 'man', phonetic_us: '/mæn/', phonetic_uk: '/mæn/', chinese: '男人', example: 'That man is my father.', level: 0, tag: '人物' },
	{ word: 'woman', phonetic_us: '/ˈwʊmən/', phonetic_uk: '/ˈwʊmən/', chinese: '女人', example: 'The woman is a teacher.', level: 0, tag: '人物' },
	{ word: 'child', phonetic_us: '/tʃaɪld/', phonetic_uk: '/tʃaɪld/', chinese: '孩子', example: 'The child is playing.', level: 0, tag: '人物' },
	{ word: 'friend', phonetic_us: '/frend/', phonetic_uk: '/frend/', chinese: '朋友', example: 'She is my best friend.', level: 0, tag: '人物' },
	{ word: 'family', phonetic_us: '/ˈfæməli/', phonetic_uk: '/ˈfæməli/', chinese: '家庭', example: 'I love my family.', level: 0, tag: '人物' },
	{ word: 'house', phonetic_us: '/haʊs/', phonetic_uk: '/haʊs/', chinese: '房子', example: 'This is my house.', level: 0, tag: '物品' },
	{ word: 'book', phonetic_us: '/bʊk/', phonetic_uk: '/bʊk/', chinese: '书', example: 'I like reading books.', level: 0, tag: '物品' },
	{ word: 'cat', phonetic_us: '/kæt/', phonetic_uk: '/kæt/', chinese: '猫', example: 'The cat is sleeping.', level: 0, tag: '动物' },
	{ word: 'dog', phonetic_us: '/dɔːɡ/', phonetic_uk: '/dɒɡ/', chinese: '狗', example: 'The dog is friendly.', level: 0, tag: '动物' },
	{ word: 'food', phonetic_us: '/fuːd/', phonetic_uk: '/fuːd/', chinese: '食物', example: 'The food is delicious.', level: 0, tag: '食物' },
	{ word: 'water', phonetic_us: '/ˈwɔːtər/', phonetic_uk: '/ˈwɔːtə/', chinese: '水', example: 'Can I have some water?', level: 0, tag: '食物' },
	{ word: 'sun', phonetic_us: '/sʌn/', phonetic_uk: '/sʌn/', chinese: '太阳', example: 'The sun is very bright.', level: 0, tag: '自然' },
	{ word: 'moon', phonetic_us: '/muːn/', phonetic_uk: '/muːn/', chinese: '月亮', example: 'The moon is beautiful tonight.', level: 0, tag: '自然' },
	{ word: 'star', phonetic_us: '/stɑːr/', phonetic_uk: '/stɑː/', chinese: '星星', example: 'I can see many stars.', level: 0, tag: '自然' },
	{ word: 'day', phonetic_us: '/deɪ/', phonetic_uk: '/deɪ/', chinese: '天', example: 'Have a nice day!', level: 0, tag: '时间' },
	{ word: 'night', phonetic_us: '/naɪt/', phonetic_uk: '/naɪt/', chinese: '夜晚', example: 'Good night, sleep well.', level: 0, tag: '时间' },
	{ word: 'morning', phonetic_us: '/ˈmɔːrnɪŋ/', phonetic_uk: '/ˈmɔːnɪŋ/', chinese: '早上', example: 'Good morning!', level: 0, tag: '时间' },
	{ word: 'time', phonetic_us: '/taɪm/', phonetic_uk: '/taɪm/', chinese: '时间', example: 'What time is it?', level: 0, tag: '时间' },
	{ word: 'name', phonetic_us: '/neɪm/', phonetic_uk: '/neɪm/', chinese: '名字', example: 'What is your name?', level: 0, tag: '基础' },
	{ word: 'number', phonetic_us: '/ˈnʌmbər/', phonetic_uk: '/ˈnʌmbə/', chinese: '数字', example: 'What is your phone number?', level: 0, tag: '基础' },
	{ word: 'yes', phonetic_us: '/jes/', phonetic_uk: '/jes/', chinese: '是的', example: 'Yes, I agree.', level: 0, tag: '基础' },
	{ word: 'no', phonetic_us: '/noʊ/', phonetic_uk: '/nəʊ/', chinese: '不', example: 'No, thank you.', level: 0, tag: '基础' },
	{ word: 'one', phonetic_us: '/wʌn/', phonetic_uk: '/wʌn/', chinese: '一', example: 'I have one brother.', level: 0, tag: '数字' },
	{ word: 'two', phonetic_us: '/tuː/', phonetic_uk: '/tuː/', chinese: '二', example: 'I have two sisters.', level: 0, tag: '数字' },
	{ word: 'three', phonetic_us: '/θriː/', phonetic_uk: '/θriː/', chinese: '三', example: 'There are three cats.', level: 0, tag: '数字' },
	{ word: 'car', phonetic_us: '/kɑːr/', phonetic_uk: '/kɑː/', chinese: '汽车', example: 'I drive a car to work.', level: 0, tag: '交通' },
	{ word: 'bus', phonetic_us: '/bʌs/', phonetic_uk: '/bʌs/', chinese: '公交车', example: 'I take the bus to school.', level: 0, tag: '交通' },
	{ word: 'school', phonetic_us: '/skuːl/', phonetic_uk: '/skuːl/', chinese: '学校', example: 'I go to school every day.', level: 0, tag: '场所' },
	{ word: 'phone', phonetic_us: '/foʊn/', phonetic_uk: '/fəʊn/', chinese: '电话', example: 'Can I use your phone?', level: 0, tag: '物品' },
	{ word: 'new', phonetic_us: '/nuː/', phonetic_uk: '/njuː/', chinese: '新的', example: 'I bought a new phone.', level: 0, tag: '形容' },
	{ word: 'old', phonetic_us: '/oʊld/', phonetic_uk: '/əʊld/', chinese: '旧的/老的', example: 'This is an old book.', level: 0, tag: '形容' },

	// ===== level 1: 日常交流 =====
	{ word: 'important', phonetic_us: '/ɪmˈpɔːrtənt/', phonetic_uk: '/ɪmˈpɔːtənt/', chinese: '重要的', example: 'This is very important.', level: 1, tag: '形容' },
	{ word: 'different', phonetic_us: '/ˈdɪfrənt/', phonetic_uk: '/ˈdɪfrənt/', chinese: '不同的', example: 'They are different.', level: 1, tag: '形容' },
	{ word: 'beautiful', phonetic_us: '/ˈbjuːtɪfl/', phonetic_uk: '/ˈbjuːtɪfl/', chinese: '美丽的', example: 'What a beautiful day!', level: 1, tag: '形容' },
	{ word: 'understand', phonetic_us: '/ˌʌndərˈstænd/', phonetic_uk: '/ˌʌndəˈstænd/', chinese: '理解', example: 'I understand now.', level: 1, tag: '动词' },
	{ word: 'remember', phonetic_us: '/rɪˈmembər/', phonetic_uk: '/rɪˈmembə/', chinese: '记住', example: 'Please remember this.', level: 1, tag: '动词' },
	{ word: 'believe', phonetic_us: '/bɪˈliːv/', phonetic_uk: '/bɪˈliːv/', chinese: '相信', example: 'I believe in you.', level: 1, tag: '动词' },
	{ word: 'change', phonetic_us: '/tʃeɪndʒ/', phonetic_uk: '/tʃeɪndʒ/', chinese: '改变', example: 'I want to change my life.', level: 1, tag: '动词' },
	{ word: 'question', phonetic_us: '/ˈkwestʃən/', phonetic_uk: '/ˈkwestʃən/', chinese: '问题', example: 'I have a question.', level: 1, tag: '名词' },
	{ word: 'problem', phonetic_us: '/ˈprɑːbləm/', phonetic_uk: '/ˈprɒbləm/', chinese: '问题', example: 'What is the problem?', level: 1, tag: '名词' },
	{ word: 'history', phonetic_us: '/ˈhɪstri/', phonetic_uk: '/ˈhɪstri/', chinese: '历史', example: 'I study history at school.', level: 1, tag: '学科' },
	{ word: 'culture', phonetic_us: '/ˈkʌltʃər/', phonetic_uk: '/ˈkʌltʃə/', chinese: '文化', example: 'Chinese culture is amazing.', level: 1, tag: '社会' },
	{ word: 'people', phonetic_us: '/ˈpiːpl/', phonetic_uk: '/ˈpiːpl/', chinese: '人们', example: 'Many people live here.', level: 1, tag: '人物' },
	{ word: 'world', phonetic_us: '/wɜːrld/', phonetic_uk: '/wɜːld/', chinese: '世界', example: 'The world is very big.', level: 1, tag: '自然' },
	{ word: 'money', phonetic_us: '/ˈmʌni/', phonetic_uk: '/ˈmʌni/', chinese: '钱', example: 'I do not have enough money.', level: 1, tag: '购物' },
	{ word: 'weather', phonetic_us: '/ˈweðər/', phonetic_uk: '/ˈweðə/', chinese: '天气', example: 'The weather is nice today.', level: 1, tag: '自然' },
	{ word: 'animal', phonetic_us: '/ˈænɪml/', phonetic_uk: '/ˈænɪml/', chinese: '动物', example: 'I love animals.', level: 1, tag: '动物' },
	{ word: 'sport', phonetic_us: '/spɔːrt/', phonetic_uk: '/spɔːt/', chinese: '运动', example: 'Football is my favorite sport.', level: 1, tag: '运动' },
	{ word: 'teacher', phonetic_us: '/ˈtiːtʃər/', phonetic_uk: '/ˈtiːtʃə/', chinese: '老师', example: 'My teacher is very kind.', level: 1, tag: '人物' },
	{ word: 'student', phonetic_us: '/ˈstuːdnt/', phonetic_uk: '/ˈstjuːdnt/', chinese: '学生', example: 'I am a student.', level: 1, tag: '人物' },
	{ word: 'hospital', phonetic_us: '/ˈhɑːspɪtl/', phonetic_uk: '/ˈhɒspɪtl/', chinese: '医院', example: 'He is in the hospital.', level: 1, tag: '场所' },
	{ word: 'doctor', phonetic_us: '/ˈdɑːktər/', phonetic_uk: '/ˈdɒktə/', chinese: '医生', example: 'I need to see a doctor.', level: 1, tag: '职业' },
	{ word: 'health', phonetic_us: '/helθ/', phonetic_uk: '/helθ/', chinese: '健康', example: 'Health is very important.', level: 1, tag: '健康' },
	{ word: 'always', phonetic_us: '/ˈɔːlweɪz/', phonetic_uk: '/ˈɔːlweɪz/', chinese: '总是', example: 'I always wake up early.', level: 1, tag: '副词' },
	{ word: 'never', phonetic_us: '/ˈnevər/', phonetic_uk: '/ˈnevə/', chinese: '从不', example: 'I never eat meat.', level: 1, tag: '副词' },
	{ word: 'sometimes', phonetic_us: '/ˈsʌmtaɪmz/', phonetic_uk: '/ˈsʌmtaɪmz/', chinese: '有时', example: 'I sometimes go swimming.', level: 1, tag: '副词' },
	{ word: 'before', phonetic_us: '/bɪˈfɔːr/', phonetic_uk: '/bɪˈfɔː/', chinese: '之前', example: 'Wash your hands before eating.', level: 1, tag: '介词' },
	{ word: 'after', phonetic_us: '/ˈæftər/', phonetic_uk: '/ˈɑːftə/', chinese: '之后', example: 'I will call you after lunch.', level: 1, tag: '介词' },
	{ word: 'begin', phonetic_us: '/bɪˈɡɪn/', phonetic_uk: '/bɪˈɡɪn/', chinese: '开始', example: 'Let us begin the class.', level: 1, tag: '动词' },
	{ word: 'finish', phonetic_us: '/ˈfɪnɪʃ/', phonetic_uk: '/ˈfɪnɪʃ/', chinese: '完成', example: 'I finished my homework.', level: 1, tag: '动词' },
	{ word: 'bring', phonetic_us: '/brɪŋ/', phonetic_uk: '/brɪŋ/', chinese: '带来', example: 'Please bring your book.', level: 1, tag: '动词' },
	{ word: 'take', phonetic_us: '/teɪk/', phonetic_uk: '/teɪk/', chinese: '拿走', example: 'Take this with you.', level: 1, tag: '动词' },
	{ word: 'give', phonetic_us: '/ɡɪv/', phonetic_uk: '/ɡɪv/', chinese: '给予', example: 'Give me the pen, please.', level: 1, tag: '动词' },
	{ word: 'buy', phonetic_us: '/baɪ/', phonetic_uk: '/baɪ/', chinese: '买', example: 'I want to buy a new car.', level: 1, tag: '购物' },
	{ word: 'sell', phonetic_us: '/sel/', phonetic_uk: '/sel/', chinese: '卖', example: 'They sell fresh fruit.', level: 1, tag: '购物' },
	{ word: 'find', phonetic_us: '/faɪnd/', phonetic_uk: '/faɪnd/', chinese: '找到', example: 'I cannot find my keys.', level: 1, tag: '动词' },
	{ word: 'help', phonetic_us: '/help/', phonetic_uk: '/help/', chinese: '帮助', example: 'Can you help me?', level: 1, tag: '动词' },
	{ word: 'learn', phonetic_us: '/lɜːrn/', phonetic_uk: '/lɜːn/', chinese: '学习', example: 'I want to learn English.', level: 1, tag: '动词' },
	{ word: 'open', phonetic_us: '/ˈoʊpən/', phonetic_uk: '/ˈəʊpən/', chinese: '打开', example: 'Open the door, please.', level: 1, tag: '动词' },
	{ word: 'close', phonetic_us: '/kloʊz/', phonetic_uk: '/kləʊz/', chinese: '关闭', example: 'Close the window.', level: 1, tag: '动词' },
	{ word: 'talk', phonetic_us: '/tɔːk/', phonetic_uk: '/tɔːk/', chinese: '谈话', example: 'Let us talk about the project.', level: 1, tag: '动词' },
	{ word: 'share', phonetic_us: '/ʃer/', phonetic_uk: '/ʃeə/', chinese: '分享', example: 'I want to share my story.', level: 1, tag: '动词' },
	{ word: 'agree', phonetic_us: '/əˈɡriː/', phonetic_uk: '/əˈɡriː/', chinese: '同意', example: 'I agree with you.', level: 1, tag: '动词' },
	{ word: 'choose', phonetic_us: '/tʃuːz/', phonetic_uk: '/tʃuːz/', chinese: '选择', example: 'You can choose any color.', level: 1, tag: '动词' },
	{ word: 'idea', phonetic_us: '/aɪˈdiːə/', phonetic_uk: '/aɪˈdɪə/', chinese: '想法', example: 'That is a good idea.', level: 1, tag: '名词' },
	{ word: 'result', phonetic_us: '/rɪˈzʌlt/', phonetic_uk: '/rɪˈzʌlt/', chinese: '结果', example: 'What was the result?', level: 1, tag: '名词' },
	{ word: 'country', phonetic_us: '/ˈkʌntri/', phonetic_uk: '/ˈkʌntri/', chinese: '国家', example: 'China is a beautiful country.', level: 1, tag: '地理' },
	{ word: 'city', phonetic_us: '/ˈsɪti/', phonetic_uk: '/ˈsɪti/', chinese: '城市', example: 'Beijing is a big city.', level: 1, tag: '地理' },
	{ word: 'tree', phonetic_us: '/triː/', phonetic_uk: '/triː/', chinese: '树', example: 'There is a big tree.', level: 1, tag: '自然' },
	{ word: 'flower', phonetic_us: '/ˈflaʊər/', phonetic_uk: '/ˈflaʊə/', chinese: '花', example: 'The flowers are beautiful.', level: 1, tag: '自然' },
	{ word: 'bird', phonetic_us: '/bɜːrd/', phonetic_uk: '/bɜːd/', chinese: '鸟', example: 'The bird is singing.', level: 1, tag: '动物' },
	{ word: 'movie', phonetic_us: '/ˈmuːvi/', phonetic_uk: '/ˈmuːvi/', chinese: '电影', example: 'Let us watch a movie.', level: 1, tag: '娱乐' },
	{ word: 'music', phonetic_us: '/ˈmjuːzɪk/', phonetic_uk: '/ˈmjuːzɪk/', chinese: '音乐', example: 'I love listening to music.', level: 1, tag: '娱乐' },
	{ word: 'game', phonetic_us: '/ɡeɪm/', phonetic_uk: '/ɡeɪm/', chinese: '游戏', example: 'I like playing games.', level: 1, tag: '娱乐' },
	{ word: 'team', phonetic_us: '/tiːm/', phonetic_uk: '/tiːm/', chinese: '团队', example: 'Our team won the game.', level: 1, tag: '运动' },
	{ word: 'class', phonetic_us: '/klæs/', phonetic_uk: '/klɑːs/', chinese: '班级/课', example: 'There are 40 students in our class.', level: 1, tag: '学习' },
	{ word: 'exam', phonetic_us: '/ɪɡˈzæm/', phonetic_uk: '/ɪɡˈzæm/', chinese: '考试', example: 'The exam is tomorrow.', level: 1, tag: '学习' },

	// ===== level 2: 进阶词汇 =====
	{ word: 'environment', phonetic_us: '/ɪnˈvaɪrənmənt/', phonetic_uk: '/ɪnˈvaɪrənmənt/', chinese: '环境', example: 'We must protect the environment.', level: 2, tag: '社会' },
	{ word: 'experience', phonetic_us: '/ɪkˈspɪriəns/', phonetic_uk: '/ɪkˈspɪərɪəns/', chinese: '经验', example: 'He has a lot of experience.', level: 2, tag: '名词' },
	{ word: 'opportunity', phonetic_us: '/ˌɑːpərˈtuːnəti/', phonetic_uk: '/ˌɒpəˈtjuːnɪti/', chinese: '机会', example: 'This is a great opportunity.', level: 2, tag: '名词' },
	{ word: 'technology', phonetic_us: '/tekˈnɑːlədʒi/', phonetic_uk: '/tekˈnɒlədʒi/', chinese: '科技', example: 'Technology changes our lives.', level: 2, tag: '科技' },
	{ word: 'knowledge', phonetic_us: '/ˈnɑːlɪdʒ/', phonetic_uk: '/ˈnɒlɪdʒ/', chinese: '知识', example: 'Knowledge is power.', level: 2, tag: '学习' },
	{ word: 'education', phonetic_us: '/ˌedʒuˈkeɪʃn/', phonetic_uk: '/ˌedʒuˈkeɪʃn/', chinese: '教育', example: 'Education is very important.', level: 2, tag: '学习' },
	{ word: 'information', phonetic_us: '/ˌɪnfərˈmeɪʃn/', phonetic_uk: '/ˌɪnfəˈmeɪʃn/', chinese: '信息', example: 'I need more information.', level: 2, tag: '名词' },
	{ word: 'challenge', phonetic_us: '/ˈtʃælɪndʒ/', phonetic_uk: '/ˈtʃælɪndʒ/', chinese: '挑战', example: 'Life is full of challenges.', level: 2, tag: '名词' },
	{ word: 'success', phonetic_us: '/səkˈses/', phonetic_uk: '/səkˈses/', chinese: '成功', example: 'Hard work leads to success.', level: 2, tag: '名词' },
	{ word: 'confidence', phonetic_us: '/ˈkɑːnfɪdəns/', phonetic_uk: '/ˈkɒnfɪdəns/', chinese: '自信', example: 'Confidence is the key to success.', level: 2, tag: '品质' },
	{ word: 'courage', phonetic_us: '/ˈkɜːrɪdʒ/', phonetic_uk: '/ˈkʌrɪdʒ/', chinese: '勇气', example: 'It takes courage to try.', level: 2, tag: '品质' },
	{ word: 'freedom', phonetic_us: '/ˈfriːdəm/', phonetic_uk: '/ˈfriːdəm/', chinese: '自由', example: 'Freedom is very precious.', level: 2, tag: '品质' },
	{ word: 'strategy', phonetic_us: '/ˈstrætədʒi/', phonetic_uk: '/ˈstrætədʒi/', chinese: '策略', example: 'What is your strategy?', level: 2, tag: '商业' },
	{ word: 'research', phonetic_us: '/rɪˈsɜːrtʃ/', phonetic_uk: '/rɪˈsɜːtʃ/', chinese: '研究', example: 'Scientific research is important.', level: 2, tag: '学术' },
	{ word: 'innovation', phonetic_us: '/ˌɪnəˈveɪʃn/', phonetic_uk: '/ˌɪnəˈveɪʃn/', chinese: '创新', example: 'Innovation drives progress.', level: 2, tag: '商业' },
	{ word: 'communication', phonetic_us: '/kəˌmjuːnɪˈkeɪʃn/', phonetic_uk: '/kəˌmjuːnɪˈkeɪʃn/', chinese: '沟通', example: 'Good communication is important.', level: 2, tag: '社交' },
	{ word: 'development', phonetic_us: '/dɪˈveləpmənt/', phonetic_uk: '/dɪˈveləpmənt/', chinese: '发展', example: 'Economic development is fast.', level: 2, tag: '社会' },
	{ word: 'achievement', phonetic_us: '/əˈtʃiːvmənt/', phonetic_uk: '/əˈtʃiːvmənt/', chinese: '成就', example: 'This is a great achievement.', level: 2, tag: '名词' },
	{ word: 'advantage', phonetic_us: '/ədˈvæntɪdʒ/', phonetic_uk: '/ədˈvɑːntɪdʒ/', chinese: '优势', example: 'What are the advantages?', level: 2, tag: '名词' },
	{ word: 'necessary', phonetic_us: '/ˈnesəseri/', phonetic_uk: '/ˈnesəsəri/', chinese: '必要的', example: 'Is this necessary?', level: 2, tag: '形容' },
	{ word: 'influence', phonetic_us: '/ˈɪnfluəns/', phonetic_uk: '/ˈɪnfluəns/', chinese: '影响', example: 'Parents influence their children.', level: 2, tag: '动词' },
	{ word: 'situation', phonetic_us: '/ˌsɪtʃuˈeɪʃn/', phonetic_uk: '/ˌsɪtʃuˈeɪʃn/', chinese: '情况', example: 'What is the situation?', level: 2, tag: '名词' },
	{ word: 'government', phonetic_us: '/ˈɡʌvərnmənt/', phonetic_uk: '/ˈɡʌvənmənt/', chinese: '政府', example: 'The government made a decision.', level: 2, tag: '社会' },
	{ word: 'society', phonetic_us: '/səˈsaɪəti/', phonetic_uk: '/səˈsaɪəti/', chinese: '社会', example: 'We live in a modern society.', level: 2, tag: '社会' },
	{ word: 'economy', phonetic_us: '/ɪˈkɑːnəmi/', phonetic_uk: '/ɪˈkɒnəmi/', chinese: '经济', example: 'The economy is growing.', level: 2, tag: '商业' },
	{ word: 'tradition', phonetic_us: '/trəˈdɪʃn/', phonetic_uk: '/trəˈdɪʃn/', chinese: '传统', example: 'This is an old tradition.', level: 2, tag: '文化' },
	{ word: 'memory', phonetic_us: '/ˈmeməri/', phonetic_uk: '/ˈmeməri/', chinese: '记忆', example: 'I have a good memory.', level: 2, tag: '名词' },
	{ word: 'imagination', phonetic_us: '/ɪˌmædʒɪˈneɪʃn/', phonetic_uk: '/ɪˌmædʒɪˈneɪʃn/', chinese: '想象力', example: 'Use your imagination.', level: 2, tag: '名词' },
	{ word: 'personality', phonetic_us: '/ˌpɜːrsəˈnæləti/', phonetic_uk: '/ˌpɜːsəˈnæləti/', chinese: '性格', example: 'She has a nice personality.', level: 2, tag: '人物' },
	{ word: 'relationship', phonetic_us: '/rɪˈleɪʃnʃɪp/', phonetic_uk: '/rɪˈleɪʃnʃɪp/', chinese: '关系', example: 'Their relationship is good.', level: 2, tag: '社交' },
	{ word: 'efficiency', phonetic_us: '/ɪˈfɪʃnsi/', phonetic_uk: '/ɪˈfɪʃnsi/', chinese: '效率', example: 'We need to improve efficiency.', level: 2, tag: '商业' },
	{ word: 'analysis', phonetic_us: '/əˈnæləsɪs/', phonetic_uk: '/əˈnæləsɪs/', chinese: '分析', example: 'The analysis is very detailed.', level: 2, tag: '学术' },
	{ word: 'discovery', phonetic_us: '/dɪˈskʌvəri/', phonetic_uk: '/dɪˈskʌvəri/', chinese: '发现', example: 'This was a great discovery.', level: 2, tag: '学术' },
	{ word: 'invention', phonetic_us: '/ɪnˈvenʃn/', phonetic_uk: '/ɪnˈvenʃn/', chinese: '发明', example: 'The internet was a great invention.', level: 2, tag: '科技' },
	{ word: 'inspiration', phonetic_us: '/ˌɪnspəˈreɪʃn/', phonetic_uk: '/ˌɪnspəˈreɪʃn/', chinese: '灵感', example: 'She is my inspiration.', level: 2, tag: '名词' },
	{ word: 'motivation', phonetic_us: '/ˌmoʊtɪˈveɪʃn/', phonetic_uk: '/ˌməʊtɪˈveɪʃn/', chinese: '动力', example: 'Motivation is the key to success.', level: 2, tag: '品质' },
	{ word: 'determination', phonetic_us: '/dɪˌtɜːrmɪˈneɪʃn/', phonetic_uk: '/dɪˌtɜːmɪˈneɪʃn/', chinese: '决心', example: 'Determination leads to success.', level: 2, tag: '品质' },
	{ word: 'compromise', phonetic_us: '/ˈkɑːmprəmaɪz/', phonetic_uk: '/ˈkɒmprəmaɪz/', chinese: '妥协', example: 'We need to find a compromise.', level: 2, tag: '社交' },
	{ word: 'accomplishment', phonetic_us: '/əˈkɑːmplɪʃmənt/', phonetic_uk: '/əˈkʌmplɪʃmənt/', chinese: '成就', example: 'This is a great accomplishment.', level: 2, tag: '名词' },
	{ word: 'atmosphere', phonetic_us: '/ˈætməsfɪr/', phonetic_uk: '/ˈætməsfɪə/', chinese: '气氛', example: 'The atmosphere was wonderful.', level: 2, tag: '名词' },
	{ word: 'philosophy', phonetic_us: '/fɪˈlɑːsəfi/', phonetic_uk: '/fɪˈlɒsəfi/', chinese: '哲学', example: 'I study philosophy at university.', level: 2, tag: '学术' },
	{ word: 'psychology', phonetic_us: '/saɪˈkɑːlədʒi/', phonetic_uk: '/saɪˈkɒlədʒi/', chinese: '心理学', example: 'Psychology helps us understand people.', level: 2, tag: '学术' },
	{ word: 'literature', phonetic_us: '/ˈlɪtərətʃər/', phonetic_uk: '/ˈlɪtrətʃə/', chinese: '文学', example: 'I enjoy reading literature.', level: 2, tag: '学术' },
	{ word: 'architecture', phonetic_us: '/ˈɑːrkɪtektʃər/', phonetic_uk: '/ˈɑːkɪtektʃə/', chinese: '建筑', example: 'The architecture is beautiful.', level: 2, tag: '艺术' },
	{ word: 'agriculture', phonetic_us: '/ˈæɡrɪkʌltʃər/', phonetic_uk: '/ˈæɡrɪkʌltʃə/', chinese: '农业', example: 'Agriculture is important for food.', level: 2, tag: '行业' },
	{ word: 'industry', phonetic_us: '/ˈɪndəstri/', phonetic_uk: '/ˈɪndəstri/', chinese: '工业', example: 'The industry is growing fast.', level: 2, tag: '行业' },
	{ word: 'transportation', phonetic_us: '/ˌtrænspərˈteɪʃn/', phonetic_uk: '/ˌtrænspɔːˈteɪʃn/', chinese: '交通', example: 'Public transportation is convenient.', level: 2, tag: '交通' },
	{ word: 'entertainment', phonetic_us: '/ˌentərˈteɪnmənt/', phonetic_uk: '/ˌentəˈteɪnmənt/', chinese: '娱乐', example: 'Entertainment is important for relaxation.', level: 2, tag: '娱乐' },
	{ word: 'adventure', phonetic_us: '/ədˈventʃər/', phonetic_uk: '/ədˈventʃə/', chinese: '冒险', example: 'Life is an adventure.', level: 2, tag: '名词' },
	{ word: 'ambition', phonetic_us: '/æmˈbɪʃn/', phonetic_uk: '/æmˈbɪʃn/', chinese: '野心', example: 'She has great ambition.', level: 2, tag: '品质' },
	{ word: 'circumstance', phonetic_us: '/ˈsɜːrkəmstæns/', phonetic_uk: '/ˈsɜːkəmstəns/', chinese: '情况', example: 'Under the circumstances, we decided to stay.', level: 2, tag: '名词' },
	{ word: 'consequence', phonetic_us: '/ˈkɑːnsəkwens/', phonetic_uk: '/ˈkɒnsɪkwəns/', chinese: '后果', example: 'There are consequences for every action.', level: 2, tag: '名词' },
	{ word: 'demonstrate', phonetic_us: '/ˈdemənstreɪt/', phonetic_uk: '/ˈdemənstreɪt/', chinese: '演示', example: 'Can you demonstrate how it works?', level: 2, tag: '动词' },
	{ word: 'eliminate', phonetic_us: '/ɪˈlɪmɪneɪt/', phonetic_uk: '/ɪˈlɪmɪneɪt/', chinese: '消除', example: 'We need to eliminate waste.', level: 2, tag: '动词' },
	{ word: 'emphasize', phonetic_us: '/ˈemfəsaɪz/', phonetic_uk: '/ˈemfəsaɪz/', chinese: '强调', example: 'I want to emphasize this point.', level: 2, tag: '动词' },
	{ word: 'entrepreneur', phonetic_us: '/ˌɑːntrəprəˈnɜːr/', phonetic_uk: '/ˌɒntrəprəˈnɜː/', chinese: '企业家', example: 'He is a successful entrepreneur.', level: 2, tag: '职业' },
	{ word: 'fundamental', phonetic_us: '/ˌfʌndəˈmentl/', phonetic_uk: '/ˌfʌndəˈmentl/', chinese: '基本的', example: 'This is a fundamental principle.', level: 2, tag: '形容' },
	{ word: 'hypothesis', phonetic_us: '/haɪˈpɑːθəsɪs/', phonetic_uk: '/haɪˈpɒθəsɪs/', chinese: '假设', example: 'Scientists test their hypotheses.', level: 2, tag: '学术' },
	{ word: 'illustrate', phonetic_us: '/ˈɪləstreɪt/', phonetic_uk: '/ˈɪləstreɪt/', chinese: '说明', example: 'Let me illustrate with an example.', level: 2, tag: '动词' },
	{ word: 'implement', phonetic_us: '/ˈɪmplɪment/', phonetic_uk: '/ˈɪmplɪment/', chinese: '实施', example: 'We need to implement the plan.', level: 2, tag: '动词' },
	{ word: 'inevitable', phonetic_us: '/ɪnˈevɪtəbl/', phonetic_uk: '/ɪnˈevɪtəbl/', chinese: '不可避免的', example: 'Change is inevitable.', level: 2, tag: '形容' },
	{ word: 'investigate', phonetic_us: '/ɪnˈvestɪɡeɪt/', phonetic_uk: '/ɪnˈvestɪɡeɪt/', chinese: '调查', example: 'Police are investigating the case.', level: 2, tag: '动词' },
	{ word: 'legitimate', phonetic_us: '/ləˈdʒɪtɪmət/', phonetic_uk: '/lɪˈdʒɪtɪmət/', chinese: '合法的', example: 'Is this a legitimate business?', level: 2, tag: '形容' },
	{ word: 'observation', phonetic_us: '/ˌɑːbzərˈveɪʃn/', phonetic_uk: '/ˌɒbzəˈveɪʃn/', chinese: '观察', example: 'Your observation is correct.', level: 2, tag: '名词' },
	{ word: 'perspective', phonetic_us: '/pərˈspektɪv/', phonetic_uk: '/pəˈspektɪv/', chinese: '观点', example: 'Let me share my perspective.', level: 2, tag: '名词' },
	{ word: 'relevant', phonetic_us: '/ˈreləvənt/', phonetic_uk: '/ˈreləvənt/', chinese: '相关的', example: 'Is this information relevant?', level: 2, tag: '形容' },
	{ word: 'responsible', phonetic_us: '/rɪˈspɑːnsəbl/', phonetic_uk: '/rɪˈspɒnsəbl/', chinese: '负责的', example: 'Who is responsible for this?', level: 2, tag: '形容' },
	{ word: 'significant', phonetic_us: '/sɪɡˈnɪfɪkənt/', phonetic_uk: '/sɪɡˈnɪfɪkənt/', chinese: '重要的', example: 'This is a significant discovery.', level: 2, tag: '形容' },
	{ word: 'sophisticated', phonetic_us: '/səˈfɪstɪkeɪtɪd/', phonetic_uk: '/səˈfɪstɪkeɪtɪd/', chinese: '复杂的', example: 'This is a sophisticated system.', level: 2, tag: '形容' },
	{ word: 'temporary', phonetic_us: '/ˈtempəreri/', phonetic_uk: '/ˈtemprəri/', chinese: '暂时的', example: 'This is a temporary solution.', level: 2, tag: '形容' },
	{ word: 'transform', phonetic_us: '/trænsˈfɔːrm/', phonetic_uk: '/trænsˈfɔːm/', chinese: '转变', example: 'Technology can transform our lives.', level: 2, tag: '动词' },
	{ word: 'sustainable', phonetic_us: '/səˈsteɪnəbl/', phonetic_uk: '/səˈsteɪnəbl/', chinese: '可持续的', example: 'We need sustainable development.', level: 2, tag: '形容' },
	{ word: 'vulnerability', phonetic_us: '/ˌvʌlnərəˈbɪləti/', phonetic_uk: '/ˌvʌlnərəˈbɪləti/', chinese: '脆弱性', example: 'Every system has vulnerabilities.', level: 2, tag: '名词' },
	{ word: 'accommodate', phonetic_us: '/əˈkɑːmədeɪt/', phonetic_uk: '/əˈkɒmədeɪt/', chinese: '容纳', example: 'The hotel can accommodate 200 guests.', level: 2, tag: '动词' },
	{ word: 'appreciate', phonetic_us: '/əˈpriːʃieɪt/', phonetic_uk: '/əˈpriːʃieɪt/', chinese: '感激', example: 'I appreciate your help.', level: 2, tag: '动词' },
	{ word: 'collaborate', phonetic_us: '/kəˈlæbəreɪt/', phonetic_uk: '/kəˈlæbəreɪt/', chinese: '合作', example: 'Let us collaborate on this project.', level: 2, tag: '动词' },
	{ word: 'concentrate', phonetic_us: '/ˈkɑːnsntreɪt/', phonetic_uk: '/ˈkɒnsntreɪt/', chinese: '集中', example: 'Please concentrate on your work.', level: 2, tag: '动词' },
	{ word: 'controversial', phonetic_us: '/ˌkɑːntrəˈvɜːrʃl/', phonetic_uk: '/ˌkɒntrəˈvɜːʃl/', chinese: '有争议的', example: 'This is a controversial topic.', level: 2, tag: '形容' },
	{ word: 'elaborate', phonetic_us: '/ɪˈlæbərət/', phonetic_uk: '/ɪˈlæbərət/', chinese: '详细的', example: 'Can you elaborate on that?', level: 2, tag: '形容' },
	{ word: 'facilitate', phonetic_us: '/fəˈsɪlɪteɪt/', phonetic_uk: '/fəˈsɪlɪteɪt/', chinese: '促进', example: 'This will facilitate communication.', level: 2, tag: '动词' },
	{ word: 'generate', phonetic_us: '/ˈdʒenəreɪt/', phonetic_uk: '/ˈdʒenəreɪt/', chinese: '产生', example: 'We need to generate new ideas.', level: 2, tag: '动词' },
	{ word: 'highlight', phonetic_us: '/ˈhaɪlaɪt/', phonetic_uk: '/ˈhaɪlaɪt/', chinese: '突出', example: 'I want to highlight this point.', level: 2, tag: '动词' },
	{ word: 'identify', phonetic_us: '/aɪˈdentɪfaɪ/', phonetic_uk: '/aɪˈdentɪfaɪ/', chinese: '识别', example: 'Can you identify the problem?', level: 2, tag: '动词' },
	{ word: 'maintain', phonetic_us: '/meɪnˈteɪn/', phonetic_uk: '/meɪnˈteɪn/', chinese: '维持', example: 'We need to maintain quality.', level: 2, tag: '动词' },
	{ word: 'negotiate', phonetic_us: '/nɪˈɡoʊʃieɪt/', phonetic_uk: '/nɪˈɡəʊʃieɪt/', chinese: '谈判', example: 'We need to negotiate a deal.', level: 2, tag: '动词' },
	{ word: 'participate', phonetic_us: '/pɑːrˈtɪsɪpeɪt/', phonetic_uk: '/pɑːˈtɪsɪpeɪt/', chinese: '参与', example: 'Please participate in the activity.', level: 2, tag: '动词' },
	{ word: 'prioritize', phonetic_us: '/praɪˈɔːrətaɪz/', phonetic_uk: '/praɪˈɒrətaɪz/', chinese: '优先', example: 'We need to prioritize our tasks.', level: 2, tag: '动词' },
	{ word: 'recommend', phonetic_us: '/ˌrekəˈmend/', phonetic_uk: '/ˌrekəˈmend/', chinese: '推荐', example: 'I recommend this book.', level: 2, tag: '动词' },
	{ word: 'substitute', phonetic_us: '/ˈsʌbstɪtuːt/', phonetic_uk: '/ˈsʌbstɪtjuːt/', chinese: '替代', example: 'Can you substitute for me?', level: 2, tag: '动词' },
	{ word: 'supplement', phonetic_us: '/ˈsʌplɪment/', phonetic_uk: '/ˈsʌplɪmənt/', chinese: '补充', example: 'This will supplement your diet.', level: 2, tag: '名词' },
	{ word: 'tolerance', phonetic_us: '/ˈtɑːlərəns/', phonetic_uk: '/ˈtɒlərəns/', chinese: '容忍', example: 'We need more tolerance.', level: 2, tag: '名词' },
	{ word: 'whereas', phonetic_us: '/werˈæz/', phonetic_uk: '/weərˈæz/', chinese: '然而', example: 'He is tall, whereas she is short.', level: 2, tag: '连词' },
	{ word: 'withstand', phonetic_us: '/wɪðˈstænd/', phonetic_uk: '/wɪðˈstænd/', chinese: '承受', example: 'This building can withstand earthquakes.', level: 2, tag: '动词' },
];

// 导入单词到数据库
function importWords() {
	initDatabase();

	const insert = db.prepare(`
		INSERT OR REPLACE INTO words (word, phonetic_us, phonetic_uk, chinese, example, level, tag, sort_order)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)
	`);

	const insertMany = db.transaction((words) => {
		for (let i = 0; i < words.length; i++) {
			const w = words[i];
			insert.run(w.word, w.phonetic_us, w.phonetic_uk, w.chinese, w.example, w.level, w.tag, i + 1);
		}
	});

	try {
		insertMany(words);
		console.log(`✅ 成功导入 ${words.length} 个单词`);

		// 统计各等级数量
		const stats = db.prepare('SELECT level, COUNT(*) as count FROM words GROUP BY level').all();
		stats.forEach(s => {
			const levelNames = { 0: '基础', 1: '日常', 2: '进阶' };
			console.log(`   ${levelNames[s.level] || '未知'}: ${s.count} 词`);
		});
	} catch (err) {
		console.error('❌ 导入失败:', err);
	}
}

importWords();
